# Generated by Django 3.1.5 on 2021-01-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('barthrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sqft', models.IntegerField(default=0)),
                ('garage', models.IntegerField(default=0)),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='photos')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos')),
                ('is_puslished', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Realtors.realtor')),
            ],
        ),
    ]
