# Generated by Django 3.1.2 on 2021-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='barthrooms',
            field=models.IntegerField(default=0),
        ),
    ]
