# Generated by Django 3.1.2 on 2021-02-02 08:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_auto_20210201_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
